---
# Service ClusterIp
apiVersion: v1
kind: Service
metadata:
  name: service-kch
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: api
    - port: 5432
      targetPort: 5432
      name: db
  selector:
    role: service-kch
---
# Deployment Data base postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eval-promerica-kch-db-deployment
  labels:
    app: eval-promerica-kch-db
spec:
  selector:
    matchLabels:
      app: eval-promerica-kch-db
  replicas: 1
  template:
    metadata:
      labels:
        app: eval-promerica-kch-db
        role: service-kch
    spec:
      containers:
        - name: nginx
          image: kechodev/eval-promerica-kch-db:latest
          ports:
            - containerPort: 5432
---
# Deployment API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eval-promerica-kch-api-deployment
  labels:
    app: eval-promerica-kch-api
spec:
  selector:
    matchLabels:
      app: eval-promerica-kch-api
  replicas: 1
  template:
    metadata:
      labels:
        app: eval-promerica-kch-api
        role: service-kch
    spec:
      containers:
        - name: nginx
          image: kechodev/eval-promerica-kch-api:latest
          ports:
            - containerPort: 8080