---
# Service ClusterIp
apiVersion: v1
kind: Service
metadata:
  name: service-kch
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      name: api
    - port: 5432
      targetPort: 5432
      name: db
  selector:
    role: service-kch
---
# Deployment Data base postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eval-promerica-kch-deployment
  labels:
    app: eval-promerica-kch
spec:
  selector:
    matchLabels:
      app: eval-promerica-kch
  replicas: 1
  template:
    metadata:
      labels:
        app: eval-promerica-kch
        role: service-kch
    spec:
      containers:
        - name: evalpromericakchdb
          image: kechodev/eval_promerica_kch_db:latest
          ports:
            - containerPort: 5432
        - name: evalpromericakchapi
          image: kechodev/eval_promerica_kch_api:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "200Mi"
            limits:
              memory: "300Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eval-promerica-kch-as
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eval-promerica-kch-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: ram
        target:
          type: Utilization
          averageUtilization: 80