---
server:
  port: 8080
---
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,America/Guayaquil
---
spring:
  jackson:
    time-zone: America/Guayaquil
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/eval_promerica_kch_db
    username: eval_promerica_kch_usr
    password: eval_promerica_kch_pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
---
application:
  open-weather:
    api-key: d669ad83acd01833d9545c9136c7dbaf
    uri: https://api.openweathermap.org/data/2.5/weather?lat=%s&lon=%s&appid=%s
  security:
    jwt:
      secret-key: 0a32dc64952e6a9a6de1c49a00fe2ff2d987cee244618df77753923fb39f8119
      expiration: 86400000 # one day
      refresh-token:
        expiration: 604800000 # 7 days